(utt.save.wave (SayText "Here is an example about speech rate") "intro.wav" 'riff)
(Parameter.set 'Duration_Stretch 2.2)
(utt.save.wave (SayText "Do you find this speech too slow?") "slow.wav" 'riff)
(Parameter.set 'Duration_Stretch 0.8)
(utt.save.wave (SayText "Or perhaps it is far too fast?") "fast.wav" 'riff) 
(set! duffint_params '((start 150) (end 150)))
(Parameter.set 'Int_Method 'DuffInt)
(Parameter.set 'Int_Target_Method Int_Targets_Default)
(utt.save.wave (SayText "But is fast monotone that I find the worst.") "mono.wav" 'riff)
